// Generated by commonXcode.sh

let PYTHONPATH = ":/nix/store/gvfj071bb4j1r0p9ylvrsl9r5i8rjimy-PyGiNaC/lib/python3.9/site-packages:/nix/store/3dgx8gcadpl9xj9c1dx2bapdg9pmj54i-python3.9-sympy-1.9/lib/python3.9/site-packages:/nix/store/p3c7zc2v5x71jffzylihlcw3cwkv5abw-python3.9-mpmath-1.2.1/lib/python3.9/site-packages:/nix/store/w2qwq98wva0ylwnawihq2l8k6r9j8k59-python3.9-scipy-1.7.3/lib/python3.9/site-packages:/nix/store/5xs5sip9i1r4rib8jdyx1dj7hn48dsak-python3.9-numpy-1.21.5/lib/python3.9/site-packages"
